hello: hello.c
	clang -o hello hello.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

compare: compare.c
	clang -o compare compare.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

agree: agree.c
	clang -o agree agree.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

cat: cat.c
	clang -o cat cat.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

pyramid: pyramid.c
	clang -o pyramid pyramid.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

calculator: calculator.c
	clang -o calculator calculator.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50