search: search.c
	clang -o search search.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

phonebook: phonebook.c
	clang -o phonebook phonebook.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

iteration: iteration.c
	clang -o iteration iteration.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

recursion: recursion.c
	clang -o recursion recursion.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

