hello: hello.c
	clang -o hello hello.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

bugs: bugs.c
	clang -o bugs bugs.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

scores: scores.c
	clang -o scores scores.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

hi: hi.c
	clang -o hi hi.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

length: length.c
	clang -o length length.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

string: string.c
	clang -o string string.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

uppercase: uppercase.c
	clang -o uppercase uppercase.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

greet: greet.c
	clang -o greet greet.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50

status: status.c
	clang -o status status.c -L"/Users/mattheuspieterstearns/Desktop/Desktop_Folder/Coding/CS50 Into to Computer Science" -lcs50