CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL, cash NUMERIC NOT NULL DEFAULT 10000.00, paymentMethod text default null);
CREATE TABLE sqlite_sequence(name,seq);
CREATE UNIQUE INDEX username ON users (username);
CREATE TABLE IF NOT EXISTS "transactions" ( id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, symbol TEXT, shares INTEGER, price NUMERIC NOT NULL, timestamp TEXT NOT NULL, type INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));