adresses: adresses.c
	clang -o adresses adresses.c -L"/Users/mattheuspieterstearns/Desktop/Desktop Folder/Coding/CS50/Intro to Computer Science" -lcs50

compare: compare.c
	clang -o compare compare.c -L"/Users/mattheuspieterstearns/Desktop/Desktop Folder/Coding/CS50/Intro to Computer Science" -lcs50

copy: copy.c
	clang -o copy copy.c -L"/Users/mattheuspieterstearns/Desktop/Desktop Folder/Coding/CS50/Intro to Computer Science" -lcs50

phonebook: phonebook.c
	clang -o phonebook phonebook.c -L"/Users/mattheuspieterstearns/Desktop/Desktop Folder/Coding/CS50/Intro to Computer Science" -lcs50